# Generated by Django 3.2 on 2021-04-25 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta de crédito', 'Tarjeta de Crédito'), ('tarjeta de débito', 'Tarjeta de Débito')], help_text='tipo pago', max_length=18)),
                ('payment_value', models.PositiveBigIntegerField(help_text='valor pago')),
                ('delivery', models.OneToOneField(help_text='entrega', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='deliveries.delivery')),
            ],
        ),
    ]
