# Generated by Django 3.2 on 2021-04-25 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='nombre', max_length=45)),
                ('historical_review', models.TextField(blank=True, help_text='reseña historica', null=True)),
                ('location', models.CharField(help_text='ubicación', max_length=45)),
                ('business_hours', models.CharField(blank=True, help_text='horario de atención', max_length=45, null=True)),
                ('status', models.BooleanField(default=True, help_text='estado')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='creado')),
            ],
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='fecha')),
                ('status', models.BooleanField(default=True, help_text='estado')),
                ('enterprise', models.ForeignKey(help_text='establecimiento', on_delete=django.db.models.deletion.CASCADE, related_name='managements', to='enterprises.enterprise')),
            ],
        ),
    ]
