# Generated by Django 3.1.7 on 2021-04-06 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='stateU',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='client',
            name='typeU',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.CharField(default='', max_length=50),
        ),
    ]
