# Generated by Django 3.1.7 on 2021-04-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210405_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='stateU',
            field=models.BooleanField(default=True),
        ),
    ]
