# Generated by Django 3.1.7 on 2021-03-29 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('payments', '__first__'),
        ('enterprises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('location', models.CharField(max_length=45)),
                ('telephone', models.CharField(max_length=15)),
                ('enterprise', models.ForeignKey(help_text='establecimiento', on_delete=django.db.models.deletion.CASCADE, related_name='couriers', to='enterprises.enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, help_text='estado')),
                ('delivery_time', models.DateTimeField(auto_now_add=True, help_text='hora entrega')),
                ('courier', models.ForeignKey(help_text='mensajero', on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='deliveries.courier')),
                ('order', models.OneToOneField(help_text='orden de pedido', on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order')),
                ('payment', models.OneToOneField(help_text='pago', on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='payments.payment')),
            ],
            options={
                'verbose_name_plural': 'deliveries',
            },
        ),
    ]
