# Generated by Django 3.2 on 2021-04-25 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_service', models.CharField(choices=[('good', 'Good'), ('regular', 'Regular'), ('bad', 'Bad')], help_text='calidad del servicio', max_length=7)),
                ('presentation', models.CharField(choices=[('good', 'Good'), ('regular', 'Regular'), ('bad', 'Bad')], help_text='presentación', max_length=7)),
                ('preparation', models.CharField(choices=[('good', 'Good'), ('regular', 'Regular'), ('bad', 'Bad')], help_text='preparación', max_length=7)),
                ('ingredients', models.CharField(choices=[('good', 'Good'), ('regular', 'Regular'), ('bad', 'Bad')], help_text='ingredientes', max_length=7)),
                ('price', models.CharField(choices=[('good', 'Good'), ('regular', 'Regular'), ('bad', 'Bad')], help_text='precio', max_length=7)),
                ('textures', models.CharField(choices=[('good', 'Good'), ('regular', 'Regular'), ('bad', 'Bad')], help_text='texturas', max_length=7)),
                ('cooking_point', models.CharField(choices=[('good', 'Good'), ('regular', 'Regular'), ('bad', 'Bad')], help_text='punto de cocción', max_length=7)),
                ('comments', models.TextField(help_text='comentarios')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='orders.order')),
            ],
        ),
    ]
