# Generated by Django 3.1.7 on 2021-03-29 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='fecha')),
                ('estimated_time', models.TimeField(help_text='tiempo estimado')),
                ('location', models.CharField(help_text='ubicación', max_length=45)),
                ('client', models.ForeignKey(help_text='cliente', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.client')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='cantidad')),
                ('order', models.ForeignKey(help_text='order de pedido', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='orders.order')),
                ('product', models.ForeignKey(help_text='producto', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='products.product')),
            ],
        ),
    ]
