# Generated by Django 3.1.7 on 2021-03-29 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='nombre', max_length=45)),
                ('price', models.PositiveBigIntegerField(help_text='precio')),
                ('ingredients', models.TextField(help_text='ingredientes')),
                ('preparation', models.TextField(blank=True, help_text='preparación', null=True)),
                ('estimated_time', models.TimeField(help_text='tiempo estimado')),
                ('accompaniments', models.ManyToManyField(help_text='acompañamientos', related_name='_product_accompaniments_+', to='products.Product')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='enterprises.enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to='')),
                ('product', models.ForeignKey(help_text='producto', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
    ]
