# Generated by Django 3.2 on 2021-04-25 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('products', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(help_text='cliente', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.client'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='productos', related_name='orders', through='orders.Detail', to='products.Product'),
        ),
        migrations.AddField(
            model_name='detail',
            name='order',
            field=models.ForeignKey(help_text='order de pedido', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='orders.order'),
        ),
        migrations.AddField(
            model_name='detail',
            name='product',
            field=models.ForeignKey(help_text='producto', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='products.product'),
        ),
    ]
