# Generated by Django 3.2 on 2021-04-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, help_text='estado')),
                ('delivery_time', models.DateTimeField(auto_now_add=True, help_text='hora entrega')),
            ],
            options={
                'verbose_name_plural': 'deliveries',
            },
        ),
    ]
